### ISSUE TITLE
02 Add new Challenge

### ISSUE THREAD

**Issue by salaos** [salaos/capstone-project#1]
## Value proposition

As a user
I want to add a new challenge
to be able to expand the list.

## Description

![Image](https://user-images.githubusercontent.com/123561210/227506846-1e5e7b4d-6b2e-48cb-8a38-b77e90928f81.png)

## Acceptance criteria

- [ ] Add-Button as an Overlay
- [ ] Button links to a form page (02.2)
- [ ] Form type=text inputs: "title", "description", 
      "worstcase", "bestcase" 
- [ ] Form type=range input: "level" (1-5)
- [ ] Button "save" submits form
- [ ] If form is submitted, challenge list is shown 
      with new entry on top of the list

## Tasks

- [ ] Create components/form
- [ ] Create Add-Button
- [ ] update Links
- [ ] write tests
