### ISSUE TITLE
01 List of Challenges

### ISSUE THREAD

**Issue by salaos** [salaos/capstone-project#1]
## Value proposition

As a user
I want to see a list of my saved challenges
to be able to have an overview.

## Description

![Image](https://user-images.githubusercontent.com/123561210/227248472-700f4c20-ba89-4060-b813-018bf9502ccd.png)

## Acceptance criteria

- [ ] Each Challenge is a different Card
- [ ] List is scrollable
- [ ] Each Entry has a checkbox
- [ ] Show Title, description and Level of the challenge

## Tasks

- [ ] Global Styles
- [ ] component/Card
- [ ] write tests
- [ ] Add to App

**Comment by Efendi5** [comment]
how do you get out of the view?
is there a next or previous function?
or is this maybe later?
whats with a header?

**Comment by alexWaligorski** [comment]
i love your project! this looks like a good start. I would recommend to add to tasks:
- create dummy data (data.db)
- define headline (my challenges etc.)
- how does the screen look like, when there are no challenges?
- what is the description? right now i only see a title in the wireframe. amybe remove description from this view and leave it for a later detailed view after clicking on challenge?
- are title, level and description required? maybe add comment which is required and which optional

**Comment by abieber1408** [comment]
Nice App for a Strong Person!!. I like it very much.

- Create database (db).
- Define it as an entry Form.

**Comment by LuYujin9** [comment]
the idea is very creativity and cool!  for this user story: In order to show the list, some more tasks about data should be added.

**Comment by PReichetanz** [comment]
Hi Nina,

a really good start for your user story! 🎉

I have only one thing to add: Since clicking the checkbox does not do anything for the user, I would move the implementation of the checkbox to another user story.
Besides, this would better reflect your the value proposition where you only want to create a list, not something to check or uncheck.

**Comment by alexWaligorski** [comment]
Great update!
One last suggestion, because coach Thomas gave me this advice:
Describe which tests you'd like to write.
E.g: Test if List renders a certain amout of list Elements / entries corresponding with the length of your db array/ amout of dummy-objects in your db.js
