### ISSUE TITLE
03 Show Detailpage

### ISSUE THREAD

**Issue by salaos** [salaos/capstone-project#2]
## Value proposition

As a user
I want to have a accordeon detailpage for every challenge
to be able to see more information than the title.

## Description

![Image](https://user-images.githubusercontent.com/123561210/229124342-e3241220-9e2f-488c-a108-e8e7d71861a0.png)

## Acceptance criteria

- [ ] Each Entry gets a dropdown icon
- [ ] When icon clicked: show "description" "bestcase" "worst case" and "level"
- [ ] Rotate icon when details shown
- [ ] When icon clicked again: 

## Tasks

- [ ] Create accordeon for Card Component
- [ ] embedd new Icon
- [ ] rotate & accordeon animation
- [ ] fetch data
- [ ] event handler
- [ ] write tests

**Comment by PReichetanz** [comment]
Hi Nina,

nice work!

Some thoughts of mine:
- Why do you need a form here? Your value proposition does not speak about editing anything, but only displaying information.
- I don't see an edit button in the scribble, where is it and what happens when I click on it?
- Why do you need to update links? Do you plan to display the dropdown information on a different page? I'm not sure whether this is necessary.
- Additional AC: When the drop down button is clicked again, the information is not displayed anymore.

**Comment by salaos** [comment]
> 

true - thank you for the feedback! Guess I forgot to take the point out, creating an edit-function will be the next user story.

**Comment by NinaBusz** [comment]
lgtm :)
