### ISSUE TITLE
01 List of Challenges

### ISSUE THREAD

**Issue by salaos** [salaos/capstone-project#3]
## Value proposition

As a user
I want to see a list of my saved challenges
to be able to have an overview.

## Description

<img width="393" alt="Screenshot 2023-03-24 at 11 48 03" src="https://user-images.githubusercontent.com/123561210/227501412-75d72bd5-f40d-49dc-a700-e7541cdfd16b.png">

## Acceptance criteria

- [ ] Each Challenge is a different Card
- [ ] List is scrollable
- [ ] Show Title of the challenge 

## Tasks

- [ ] Default Screen if there are no challenges 
- [ ] Global Styles
- [ ] component/Card
- [ ] write tests
- [ ] Add to App
- [ ] create dummy data (data.db)
- [ ] define headline (my challenges etc.)
